name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  connectivity_plus: ^6.1.4
  dio: ^5.8.0+1
  dio_http2_adapter: ^2.6.0
  dio_smart_retry: ^7.0.1
  uuid: ^4.5.1
  intl: any
  get_it: ^8.0.3
  flutter_dotenv: ^5.2.1
  json_annotation: ^4.9.0
  async: ^2.11.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  provider: ^6.1.4
  flutter_localizations:
    sdk: flutter
  geolocator: ^14.0.0
  geocoding: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
